In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from typing import List
from tqdm import tqdm

### 1. 2.

In [2]:
df_items = pd.read_csv('./data_en/items_en.csv').drop('Unnamed: 0', axis=1)
df_users = pd.read_csv('./data_en/users_en.csv').drop('Unnamed: 0', axis=1)
df_iters = pd.read_csv('./data_en/interactions.csv')
df_iters['last_watch_dt'] = pd.to_datetime(df_iters['last_watch_dt'])

In [3]:
df_items.head()

,item_id,content_type,title,title_orig,release_year,genres,countries,for_kids,age_rating,studios,description,keywords,actors_translated,actors_transliterated,directors_translated,transliterated
0,10711,film,Talk to her,Hable con ella,2002.0,"drama, foreign, detective, melodrama",Spain,NaN,16.0,NaN,"Marco, a journalist, interviews the famous Tor...","Talk, her, 2002, Spain, friends, love, strong,...","Adolfo Fernández, Ana Fernández, Dario Grandin...","Adol'fo Fernandes, Ana Fernandes, Dario Grandi...",Pedro Almodovar,Pedro Al'modovar
1,2508,film,Naked Peppers,Search Party,2014.0,"foreign, adventure, comedy",USA,NaN,16.0,NaN,The main character has learned not to invite h...,"Naked, Peppers, 2014, USA, friends, weddings, ...","Adam Palley, Brian Huskey, JB Smoove, Jason Ma...","Adam Palli, Brajan Haski, Dzh.B. Smuv, Dzhejso...",Scott Armstrong,Skot Armstrong
2,10716,film,Tactical force,Tactical Force,2011.0,"crime, foreign, thrillers, action, comedy",Canada,NaN,16.0,NaN,"Professional wrestler Steve Austin (""All or No...","Tactical, Force, 2011, Canada, bandits, gangst...","Adrian Holmes, Darren Shalavi, Jerry Wasserman...","Adrian Holms, Darren Shalavi, Dzherri Vasserma...",Adam P. Caltraro,Adam P. Kaltraro
3,7868,film,45 years old,45 Years,2015.0,"drama, foreign, melodrama",UK,NaN,16.0,NaN,"Charlotte Rampling, Tom Courtney, Geraldine Ja...","45, years, 2015, United Kingdom, marriage, lif...","Alexandra Riddleston-Barrett, Geraldine James,...","Aleksandra Riddlston-Barrett, Dzheral'din Dzhe...",By Andrew Hay,Endrju Hej
4,16268,film,Everything Solves in a Moment,NaN,1978.0,"drama, sport, soviet, melodrama",USSR,NaN,12.0,Lenfilm,The circle of her mentors and the most loyal f...,"Everything that decides, moment, 1978, USSR, s...","Aleksandr Abdulov, Aleksandr Demyanenko, Alexe...","Aleksandr Abdulov, Aleksandr Dem'janenko, Alek...",Victor Sadovsky,Viktor Sadovskij

In [4]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15963 entries, 0 to 15962
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   item_id                15963 non-null  int64
 1   content_type           15963 non-null  object
 2   title                  15961 non-null  object
 3   title_orig             11218 non-null  object
 4   release_year           15865 non-null  float64
 5   genres                 15963 non-null  object
 6   countries              15963 non-null  object
 7   for_kids               566 non-null    float64
 8   age_rating             15961 non-null  float64
 9   studios                1065 non-null   object
 10  description            15963 non-null  object
 11  keywords               15534 non-null  object
 12  actors_translated      13344 non-null  object
 13  actors_transliterated  13344 non-null  object
 14  directors_translated   14439 non-null  object
 15  transliterated         14454 non-null  object
dtypes: float64(3), int64(1), object(12)
memory usage: 1.9+ MB

In [5]:
df_users.head()

   user_id        age        income sex  kids_flg
0   973171  age_25_34  income_60_90   M         1
1   962099  age_18_24  income_20_40   M         0
2  1047345  age_45_54  income_40_60   F         0
3   721985  age_45_54  income_20_40   F         0
4   704055  age_35_44  income_60_90   F         0

In [6]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840197 entries, 0 to 840196
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   user_id   840197 non-null  int64
 1   age       826102 non-null  object
 2   income    825421 non-null  object
 3   sex       826366 non-null  object
 4   kids_flg  840197 non-null  int64
dtypes: int64(2), object(3)
memory usage: 32.1+ MB

In [7]:
df_iters.head()

   user_id  item_id last_watch_dt  total_dur  watched_pct
0   176549     9506    2021-05-11       4250         72.0
1   699317     1659    2021-05-29       8317        100.0
2   656683     7107    2021-05-09         10          0.0
3   864613     7638    2021-07-05      14483        100.0
4   964868     9506    2021-04-30       6725        100.0

In [8]:
df_iters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5476251 entries, 0 to 5476250
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   user_id        int64
 1   item_id        int64
 2   last_watch_dt  datetime64[ns]
 3   total_dur      int64
 4   watched_pct    float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 208.9 MB

### 3. 4.

In [9]:
df_iters_test = df_iters[df_iters['last_watch_dt'].max() - df_iters['last_watch_dt']<np.timedelta64(14)]
df_iters_test = df_iters_test.groupby('item_id').filter(lambda group: len(group) > 2)

len(df_iters_test)
#df_iters_test.head(20)

68795

In [10]:
df_iters_train = df_iters[df_iters['last_watch_dt'].max() - df_iters['last_watch_dt']>=np.timedelta64(14)]
df_iters_train = df_iters_train.groupby('item_id').filter(lambda group: len(group) > 2)

len(df_iters_train)
#df_iters_train.head(20)

5400037

In [11]:
df_users_filtred = df_iters_test.groupby('user_id').filter(lambda group: len(group) > 1 and len(group) < 20)['user_id'].unique()
all_users = df_users['user_id'].unique()

df_users_filtred = df_users_filtred[np.isin(df_users_filtred, all_users)]
df_users_filtred

array([ 626036, 1029980,  830261, ...,  371633,  967655,  214369],
      shape=(11336,))

In [12]:
df_iters_test.head(20)

      user_id  item_id last_watch_dt  total_dur  watched_pct
9      203219    13582    2021-08-22       6975        100.0
65     125519     4583    2021-08-22          3          0.0
141    626036    11109    2021-08-22       1323         19.0
277   1029980    12225    2021-08-22         15          0.0
336    830261     6646    2021-08-22         50          1.0
366    217842     5680    2021-08-22       7494        100.0
401   1001574    12149    2021-08-22        103          1.0
491    361773    15297    2021-08-22          5          0.0
575    937219     3734    2021-08-22       1343         25.0
669    780411    15297    2021-08-22       8545         63.0
758    652950    14530    2021-08-22       5478         94.0
780    649830     3259    2021-08-22        601         11.0
885    302389     5543    2021-08-22        317          5.0
1037   226536    11664    2021-08-22        620         12.0
1085   374955     4239    2021-08-22        989         17.0
1103   438258      341    2021-08-22       9366          8.0
1166   356008     2657    2021-08-22       9445         22.0
1197   913582     3800    2021-08-22         53          1.0
1221   907424    12228    2021-08-22        534          5.0
1259   119703    13600    2021-08-22       5844         74.0

In [13]:
df_iters_test[df_iters_test["user_id"]==125519]["item_id"].tolist()

[4583, 3475, 10440]

### 5.

In [14]:
def precision_at_k(recommended_list, watched_list, k=5):
    
    watched_list = np.array(watched_list)
    recommended_list = np.array(recommended_list)
    
    #assert len(watched_list) > len(recommended_list)
    watched_list = watched_list  # Тут нет [:k] !!
    recommended_list = recommended_list[:k]
    
    flags = np.isin(watched_list, recommended_list)
    
    precision = flags.sum() / len(recommended_list)
    
    
    return precision

def ap_k(recommended_list, watched_list, k=5):
    
    watched_list = np.array(watched_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(recommended_list, watched_list)
    
    if sum(flags) == 0:
        return 0
    
    sum_ = 0
    for i in range(0, k-1):
        if flags[i] == True:
            p_k = precision_at_k(recommended_list, watched_list, k=i+1)
            sum_ += p_k
            
    result = sum_ / sum(flags)
    
    return result

def map_k(recommended_list, watched_list, k=5, u=1):

    sum_ = 0
    for i in range(len(recommended_list)):
        sum_ += ap_k(recommended_list[i], watched_list[i], k)
    
    result = sum_ / u

    return result

In [15]:
ap_k([6646, 2657, 12228, 3475, 5543], df_iters_test[df_iters_test["user_id"]==125519]["item_id"].tolist(), k=6)

np.float64(0.25)

#### Random

In [16]:
df_items['item_id'].sample(n=10, replace=True).tolist()

[13156, 15905, 11356, 9433, 240, 11912, 3616, 14876, 16116, 4377]

In [17]:
watched_list = []
recommended_list = []

for user in df_iters_test['user_id'].unique():
    watched_list.append(df_iters_test[df_iters_test["user_id"]==user]["item_id"].tolist())
    recommended_list.append(df_items['item_id'].sample(n=10, replace=True).tolist())

In [18]:
map_k(recommended_list, watched_list, 10, len(df_iters_test['user_id'].unique()))

np.float64(0.000267965812198922)

#### Popular

In [23]:
df_iters_train['item_id'].value_counts().head(10).reset_index()['item_id'].tolist()

[10440, 15297, 9728, 13865, 4151, 3734, 2657, 4880, 142, 6809]

In [25]:
watched_list = []
recommended_list = []

l = len(df_iters_test['user_id'].unique())
total_recs = df_iters_train['item_id'].value_counts().head(10).reset_index()['item_id'].tolist()
for i, user in enumerate(df_iters_test['user_id'].unique()):
    watched_list.append(df_iters_test[df_iters_test["user_id"]==user]["item_id"].tolist())
    recommended_list.append(total_recs)
    print(f'{i}/{l}')

0/41903
1/41903
2/41903
3/41903
4/41903
5/41903
6/41903
7/41903
8/41903
9/41903
10/41903
11/41903
12/41903
13/41903
14/41903
15/41903
16/41903
17/41903
18/41903
19/41903
20/41903
21/41903
22/41903
23/41903
24/41903
25/41903
26/41903
27/41903
28/41903
29/41903
30/41903
31/41903
32/41903
33/41903
34/41903
35/41903
36/41903
37/41903
38/41903
39/41903
40/41903
41/41903
42/41903
43/41903
44/41903
45/41903
46/41903
47/41903
48/41903
49/41903
50/41903
51/41903
52/41903
53/41903
54/41903
55/41903
56/41903
57/41903
58/41903
59/41903
60/41903
61/41903
62/41903
63/41903
64/41903
65/41903
66/41903
67/41903
68/41903
69/41903
70/41903
71/41903
72/41903
73/41903
74/41903
75/41903
76/41903
77/41903
78/41903
79/41903
80/41903
81/41903
82/41903
83/41903
84/41903
85/41903
86/41903
87/41903
88/41903
89/41903
90/41903
91/41903
92/41903
93/41903
94/41903
95/41903
96/41903
97/41903
98/41903
99/41903
100/41903
101/41903
102/41903
103/41903
104/41903
105/41903
106/41903
107/41903
108/41903
109/41903
110/41903
111/41903
112/41903
113/41903
114/41903
115/41903
116/41903
117/41903
118/41903
119/41903
120/41903
121/41903
122/41903
123/41903
124/41903
125/41903
126/41903
127/41903
128/41903
129/41903
130/41903
131/41903
132/41903
133/41903
134/41903
135/41903
136/41903
137/41903
138/41903
139/41903
140/41903
141/41903
142/41903
143/41903
144/41903
145/41903
146/41903
147/41903
148/41903
149/41903
150/41903
151/41903
152/41903
153/41903
154/41903
155/41903
156/41903
157/41903
158/41903
159/41903
160/41903
161/41903
162/41903
163/41903
164/41903
165/41903
166/41903
167/41903
168/41903
169/41903
170/41903
171/41903
172/41903
173/41903
174/41903
175/41903
176/41903
177/41903
178/41903
179/41903
180/41903
181/41903
182/41903
183/41903
184/41903
185/41903
186/41903
187/41903
188/41903
189/41903
190/41903
191/41903
192/41903
193/41903
194/41903
195/41903
196/41903
197/41903
198/41903
199/41903
200/41903
201/41903
202/41903
203/41903
204/41903
205/41903
206/41903
207/41903
208/41903
209/41903
210/41903
211/41903
212/41903
213/41903
214/41903
215/41903
216/41903
217/41903
218/41903
219/41903
220/41903
221/41903
222/41903
223/41903
224/41903
225/41903
226/41903
227/41903
228/41903
229/41903
230/41903
231/41903
232/41903
233/41903
234/41903
235/41903
236/41903
237/41903
238/41903
239/41903
240/41903
241/41903
242/41903
243/41903
244/41903
245/41903
246/41903
247/41903
248/41903
249/41903
250/41903
251/41903
252/41903
253/41903
254/41903
255/41903
256/41903
257/41903
258/41903
259/41903
260/41903
261/41903
262/41903
263/41903
264/41903
265/41903
266/41903
267/41903
268/41903
269/41903
270/41903
271/41903
272/41903
273/41903
274/41903
275/41903
276/41903
277/41903
278/41903
279/41903
280/41903
281/41903
282/41903
283/41903
284/41903
285/41903
286/41903
287/41903
288/41903
289/41903
290/41903
291/41903
292/41903
293/41903
294/41903
295/41903
296/41903
297/41903
298/41903
299/41903
300/41903
301/41903
302/41903
303/41903
304/41903
305/41903
306/41903
307/41903
308/41903
309/41903
310/41903
311/41903
312/41903
313/41903
314/41903
315/41903
316/41903
317/41903
318/41903
319/41903
320/41903
321/41903
322/41903
323/41903
324/41903
325/41903
326/41903
327/41903
328/41903
329/41903
330/41903
331/41903
332/41903
333/41903
334/41903
335/41903
336/41903
337/41903
338/41903
339/41903
340/41903
341/41903
342/41903
343/41903
344/41903
345/41903
346/41903
347/41903
348/41903
349/41903
350/41903
351/41903
352/41903
353/41903
354/41903
355/41903
356/41903
357/41903
358/41903
359/41903
360/41903
361/41903
362/41903
363/41903
364/41903
365/41903
366/41903
367/41903
368/41903
369/41903
370/41903
371/41903
372/41903
373/41903
374/41903
375/41903
376/41903
377/41903
378/41903
379/41903
380/41903
381/41903
382/41903
383/41903
384/41903
385/41903
386/41903
387/41903
388/41903
389/41903
390/41903
391/41903
392/41903
393/41903
394/41903
395/41903
396/41903
397/41903
398/41903
399/41903
400/41903
401/41903
402/41903
403/41903
404/41903
405/41903
406/41903
407/41903
408/41903
409/41903
410/41903
411/41903
412/41903
413/41903
414/41903
415/41903
416/41903
417/41903
418/41903
419/41903
420/41903
421/41903
422/41903
423/41903
424/41903
425/41903
426/41903
427/41903
428/41903
429/41903
430/41903
431/41903
432/41903
433/41903
434/41903
435/41903
436/41903
437/41903
438/41903
439/41903
440/41903
441/41903
442/41903
443/41903
444/41903
445/41903
446/41903
447/41903
448/41903
449/41903
450/41903
451/41903
452/41903
453/41903
454/41903
455/41903
456/41903
457/41903
458/41903
459/41903
460/41903
461/41903
462/41903
463/41903
464/41903
465/41903
466/41903
467/41903
468/41903
469/41903
470/41903
471/41903
472/41903
473/41903
474/41903
475/41903
476/41903
477/41903
478/41903
479/41903
480/41903
481/41903
482/41903
483/41903
484/41903
485/41903
486/41903
487/41903
488/41903
489/41903
490/41903
491/41903
492/41903
493/41903
494/41903
495/41903
496/41903
497/41903
498/41903
499/41903
500/41903
501/41903
502/41903
503/41903
504/41903
505/41903
506/41903
507/41903
508/41903
509/41903
510/41903
511/41903
512/41903
513/41903
514/41903
515/41903
516/41903
517/41903
518/41903
519/41903
520/41903
521/41903
522/41903
523/41903
524/41903
525/41903
526/41903
527/41903
528/41903
529/41903
530/41903
531/41903
532/41903
533/41903
534/41903
535/41903
536/41903
537/41903
538/41903
539/41903
540/41903
541/41903
542/41903
543/41903
544/41903
545/41903
546/41903
547/41903
548/41903
549/41903
550/41903
551/41903
552/41903
553/41903
554/41903
555/41903
556/41903
557/41903
558/41903
559/41903
560/41903
561/41903
562/41903
563/41903
564/41903
565/41903
566/41903
567/41903
568/41903
569/41903
570/41903
571/41903
572/41903
573/41903
574/41903
575/41903
576/41903
577/41903
578/41903
579/41903
580/41903
581/41903
582/41903
583/41903
584/41903
585/41903
586/41903
587/41903
588/41903
589/41903
590/41903
591/41903
592/41903
593/41903
594/41903
595/41903
596/41903
597/41903
598/41903
599/41903
600/41903
601/41903
602/41903
603/41903
604/41903
605/41903
606/41903
607/41903
608/41903
609/41903
610/41903
611/41903
612/41903
613/41903
614/41903
615/41903
616/41903
617/41903
618/41903
619/41903
620/41903
621/41903
622/41903
623/41903
624/41903
625/41903
626/41903
627/41903
628/41903
629/41903
630/41903
631/41903
632/41903
633/41903
634/41903
635/41903
636/41903
637/41903
638/41903
639/41903
640/41903
641/41903
642/41903
643/41903
644/41903
645/41903
646/41903
647/41903
648/41903
649/41903
650/41903
651/41903
652/41903
653/41903
654/41903
655/41903
656/41903
657/41903
658/41903
659/41903
660/41903
661/41903
662/41903
663/41903
664/41903
665/41903
666/41903
667/41903
668/41903
669/41903
670/41903
671/41903
672/41903
673/41903
674/41903
675/41903
676/41903
677/41903
678/41903
679/41903
680/41903
681/41903
682/41903
683/41903
684/41903
685/41903
686/41903
687/41903
688/41903
689/41903
690/41903
691/41903
692/41903
693/41903
694/41903
695/41903
696/41903
697/41903
698/41903
699/41903
700/41903
701/41903
702/41903
703/41903
704/41903
705/41903
706/41903
707/41903
708/41903
709/41903
710/41903
711/41903
712/41903
713/41903
714/41903
715/41903
716/41903
717/41903
718/41903
719/41903
720/41903
721/41903
722/41903
723/41903
724/41903
725/41903
726/41903
727/41903
728/41903
729/41903
730/41903
731/41903
732/41903
733/41903
734/41903
735/41903
736/41903
737/41903
738/41903
739/41903
740/41903
741/41903
742/41903
743/41903
744/41903
745/41903
746/41903
747/41903
748/41903
749/41903
750/41903
751/41903
752/41903
753/41903
754/41903
755/41903
756/41903
757/41903
758/41903
759/41903
760/41903
761/41903
762/41903
763/41903
764/41903
765/41903
766/41903
767/41903
768/41903
769/41903
770/41903
771/41903
772/41903
773/41903
774/41903
775/41903
776/41903
777/41903
778/41903
779/41903
780/41903
781/41903
782/41903
783/41903
784/41903
785/41903
786/41903
787/41903
788/41903
789/41903
790/41903
791/41903
792/41903
793/41903
794/41903
795/41903
796/41903
797/41903
798/41903
799/41903
800/41903
801/41903
802/41903
803/41903
804/41903
805/41903
806/41903
807/41903
808/41903
809/41903
810/41903
811/41903
812/41903
813/41903
814/41903
815/41903
816/41903
817/41903
818/41903
819/41903
820/41903
821/41903
822/41903
823/41903
824/41903
825/41903
826/41903
827/41903
828/41903
829/41903
830/41903
831/41903
832/41903
833/41903
834/41903
835/41903
836/41903
837/41903
838/41903
839/41903
840/41903
841/41903
842/41903
843/41903
844/41903
845/41903
846/41903
847/41903
848/41903
849/41903
850/41903
851/41903
852/41903
853/41903
854/41903
855/41903
856/41903
857/41903
858/41903
859/41903
860/41903
861/41903
862/41903
863/41903
864/41903
865/41903
866/41903
867/41903
868/41903
869/41903
870/41903
871/41903
872/41903
873/41903
874/41903
875/41903
876/41903
877/41903
878/41903
879/41903
880/41903
881/41903
882/41903
883/41903
884/41903
885/41903
886/41903
887/41903
888/41903
889/41903
890/41903
891/41903
892/41903
893/41903
894/41903
895/41903
896/41903
897/41903
898/41903
899/41903
900/41903
901/41903
902/41903
903/41903
904/41903
905/41903
906/41903
907/41903
908/41903
909/41903
910/41903
911/41903
912/41903
913/41903
914/41903
915/41903
916/41903
917/41903
918/41903
919/41903
920/41903
921/41903
922/41903
923/41903
924/41903
925/41903
926/41903
927/41903
928/41903
929/41903
930/41903
931/41903
932/41903
933/41903
934/41903
935/41903
936/41903
937/41903
938/41903
939/41903
940/41903
941/41903
942/41903
943/41903
944/41903
945/41903
946/41903
947/41903
948/41903
949/41903
950/41903
951/41903
952/41903
953/41903
954/41903
955/41903
956/41903
957/41903
958/41903
959/41903
960/41903
961/41903
962/41903
963/41903
964/41903
965/41903
966/41903
967/41903
968/41903
969/41903
970/41903
971/41903
972/41903
973/41903
974/41903
975/41903
976/41903
977/41903
978/41903
979/41903
980/41903
981/41903
982/41903
983/41903
984/41903
985/41903
986/41903
987/41903
988/41903
989/41903
990/41903
991/41903
992/41903
993/41903
994/41903
995/41903
996/41903
997/41903
998/41903
999/41903
1000/41903
1001/41903
1002/41903
1003/41903
1004/41903
1005/41903
1006/41903
1007/41903
1008/41903
1009/41903
1010/41903
1011/41903
1012/41903
1013/41903
1014/41903
1015/41903
1016/41903
1017/41903
1018/41903
1019/41903
1020/41903
1021/41903
1022/41903
1023/41903
1024/41903
1025/41903
1026/41903
1027/41903
1028/41903
1029/41903
1030/41903
1031/41903
1032/41903
1033/41903
1034/41903
1035/41903
1036/41903
1037/41903
1038/41903
1039/41903
1040/41903
1041/41903
1042/41903
1043/41903
1044/41903
1045/41903
1046/41903
1047/41903
1048/41903
1049/41903
1050/41903
1051/41903
1052/41903
1053/41903
1054/41903
1055/41903
1056/41903
1057/41903
1058/41903
1059/41903
1060/41903
1061/41903
1062/41903
1063/41903
1064/41903
1065/41903
1066/41903
1067/41903
1068/41903
1069/41903
1070/41903
1071/41903
1072/41903
1073/41903
1074/41903
1075/41903
1076/41903
1077/41903
1078/41903
1079/41903
1080/41903
1081/41903
1082/41903
1083/41903
1084/41903
1085/41903
1086/41903
1087/41903
1088/41903
1089/41903
1090/41903
1091/41903
1092/41903
1093/41903
1094/41903
1095/41903
1096/41903
1097/41903
1098/41903
1099/41903
1100/41903
1101/41903
1102/41903
1103/41903
1104/41903
1105/41903
1106/41903
1107/41903
1108/41903
1109/41903
1110/41903
1111/41903
1112/41903
1113/41903
1114/41903
1115/41903
1116/41903
1117/41903
1118/41903
1119/41903
1120/41903
1121/41903
1122/41903
1123/41903
1124/41903
1125/41903
1126/41903
1127/41903
1128/41903
1129/41903
1130/41903
1131/41903
1132/41903
1133/41903
1134/41903
1135/41903
1136/41903
1137/41903
1138/41903
1139/41903
1140/41903
1141/41903
1142/41903
1143/41903
1144/41903
1145/41903
1146/41903
1147/41903
1148/41903
1149/41903
1150/41903
1151/41903
1152/41903
1153/41903
1154/41903
1155/41903
1156/41903
1157/41903
1158/41903
1159/41903
1160/41903
1161/41903
1162/41903
1163/41903
1164/41903
1165/41903
1166/41903
1167/41903
1168/41903
1169/41903
1170/41903
1171/41903
1172/41903
1173/41903
1174/41903
1175/41903
1176/41903
1177/41903
1178/41903
1179/41903
1180/41903
1181/41903
1182/41903
1183/41903
1184/41903
1185/41903
1186/41903
1187/41903
1188/41903
1189/41903
1190/41903
1191/41903
1192/41903
1193/41903
1194/41903
1195/41903
1196/41903
1197/41903
1198/41903
1199/41903
1200/41903
1201/41903
1202/41903
1203/41903
1204/41903
1205/41903
1206/41903
1207/41903
1208/41903
1209/41903
1210/41903
1211/41903
1212/41903
1213/41903
1214/41903
1215/41903
1216/41903
1217/41903
1218/41903
1219/41903
1220/41903
1221/41903
1222/41903
1223/41903
1224/41903
1225/41903
1226/41903
1227/41903
1228/41903
1229/41903
1230/41903
1231/41903
1232/41903
1233/41903
1234/41903
1235/41903
1236/41903
1237/41903
1238/41903
1239/41903
1240/41903
1241/41903
1242/41903
1243/41903
1244/41903
1245/41903
1246/41903
1247/41903
1248/41903
1249/41903
1250/41903
1251/41903
1252/41903
1253/41903
1254/41903
1255/41903
1256/41903
1257/41903
1258/41903
1259/41903
1260/41903
1261/41903
1262/41903
1263/41903
1264/41903
1265/41903
1266/41903
1267/41903
1268/41903
1269/41903
1270/41903
1271/41903
1272/41903
1273/41903
1274/41903
1275/41903
1276/41903
1277/41903
1278/41903
1279/41903
1280/41903
1281/41903
1282/41903
1283/41903
1284/41903
1285/41903
1286/41903
1287/41903
1288/41903
1289/41903
1290/41903
1291/41903
1292/41903
1293/41903
1294/41903
1295/41903
1296/41903
1297/41903
1298/41903
1299/41903
1300/41903
1301/41903
1302/41903
1303/41903
1304/41903
1305/41903
1306/41903
1307/41903
1308/41903
1309/41903
1310/41903
1311/41903
1312/41903
1313/41903
1314/41903
1315/41903
1316/41903
1317/41903
1318/41903
1319/41903
1320/41903
1321/41903
1322/41903
1323/41903
1324/41903
1325/41903
1326/41903
1327/41903
1328/41903
1329/41903
1330/41903
1331/41903
1332/41903
1333/41903
1334/41903
1335/41903
1336/41903
1337/41903
1338/41903
1339/41903
1340/41903
1341/41903
1342/41903
1343/41903
1344/41903
1345/41903
1346/41903
1347/41903
1348/41903
1349/41903
1350/41903
1351/41903
1352/41903
1353/41903
1354/41903
1355/41903
1356/41903
1357/41903
1358/41903
1359/41903
1360/41903
1361/41903
1362/41903
1363/41903
1364/41903
1365/41903
1366/41903
1367/41903
1368/41903
1369/41903
1370/41903
1371/41903
1372/41903
1373/41903
1374/41903
1375/41903
1376/41903
1377/41903
1378/41903
1379/41903
1380/41903
1381/41903
1382/41903
1383/41903
1384/41903
1385/41903
1386/41903
1387/41903
1388/41903
1389/41903
1390/41903
1391/41903
1392/41903
1393/41903
1394/41903
1395/41903
1396/41903
1397/41903
1398/41903
1399/41903
1400/41903
1401/41903
1402/41903
1403/41903
1404/41903
1405/41903
1406/41903
1407/41903
1408/41903
1409/41903
1410/41903
1411/41903
1412/41903
1413/41903
1414/41903
1415/41903
1416/41903
1417/41903
1418/41903
1419/41903
1420/41903
1421/41903
1422/41903
1423/41903
1424/41903
1425/41903
1426/41903
1427/41903
1428/41903
1429/41903
1430/41903
1431/41903
1432/41903
1433/41903
1434/41903
1435/41903
1436/41903
1437/41903
1438/41903
1439/41903
1440/41903
1441/41903
1442/41903
1443/41903
1444/41903
1445/41903
1446/41903
1447/41903
1448/41903
1449/41903
1450/41903
1451/41903
1452/41903
1453/41903
1454/41903
1455/41903
1456/41903
1457/41903
1458/41903
1459/41903
1460/41903
1461/41903
1462/41903
1463/41903
1464/41903
1465/41903
1466/41903
1467/41903
1468/41903
1469/41903
1470/41903
1471/41903
1472/41903
1473/41903
1474/41903
1475/41903
1476/41903
1477/41903
1478/41903
1479/41903
1480/41903
1481/41903
1482/41903
1483/41903
1484/41903
1485/41903
1486/41903
1487/41903
1488/41903
1489/41903
1490/41903
1491/41903
1492/41903
1493/41903
1494/41903
1495/41903
1496/41903
1497/41903
1498/41903
1499/41903
1500/41903
1501/41903
1502/41903
1503/41903
1504/41903
1505/41903
1506/41903
1507/41903
1508/41903
1509/41903
1510/41903
1511/41903
1512/41903
1513/41903
1514/41903
1515/41903
1516/41903
1517/41903
1518/41903
1519/41903
1520/41903
1521/41903
1522/41903
1523/41903
1524/41903
1525/41903
1526/41903
1527/41903
1528/41903
1529/41903
1530/41903
1531/41903
1532/41903
1533/41903
1534/41903
1535/41903
1536/41903
1537/41903
1538/41903
1539/41903
1540/41903
1541/41903
1542/41903
1543/41903
1544/41903
1545/41903
1546/41903
1547/41903
1548/41903
1549/41903
1550/41903
1551/41903
1552/41903
1553/41903
1554/41903
1555/41903
1556/41903
1557/41903
1558/41903
1559/41903
1560/41903
1561/41903
1562/41903
1563/41903
1564/41903
1565/41903
1566/41903
1567/41903
1568/41903
1569/41903
1570/41903
1571/41903
1572/41903
1573/41903
1574/41903
1575/41903
1576/41903
1577/41903
1578/41903
1579/41903
1580/41903
1581/41903
1582/41903
1583/41903
1584/41903
1585/41903
1586/41903
1587/41903
1588/41903
1589/41903
1590/41903
1591/41903
1592/41903
1593/41903
1594/41903
1595/41903
1596/41903
1597/41903
1598/41903
1599/41903
1600/41903
1601/41903
1602/41903
1603/41903
1604/41903
1605/41903
1606/41903
1607/41903
1608/41903
1609/41903
1610/41903
1611/41903
1612/41903
1613/41903
1614/41903
1615/41903
1616/41903
1617/41903
1618/41903
1619/41903
1620/41903
1621/41903
1622/41903
1623/41903
1624/41903
1625/41903
1626/41903
1627/41903
1628/41903
1629/41903
1630/41903
1631/41903
1632/41903
1633/41903
1634/41903
1635/41903
1636/41903
1637/41903
1638/41903
1639/41903
1640/41903
1641/41903
1642/41903
1643/41903
1644/41903
1645/41903
1646/41903
1647/41903
1648/41903
1649/41903
1650/41903
1651/41903
1652/41903
1653/41903
1654/41903
1655/41903
1656/41903
1657/41903
1658/41903
1659/41903
1660/41903
1661/41903
1662/41903
1663/41903
1664/41903
1665/41903
1666/41903
1667/41903
1668/41903
1669/41903
1670/41903
1671/41903
1672/41903
1673/41903
1674/41903
1675/41903
1676/41903
1677/41903
1678/41903
1679/41903
1680/41903
1681/41903
1682/41903
1683/41903
1684/41903
1685/41903
1686/41903
1687/41903
1688/41903
1689/41903
1690/41903
1691/41903
1692/41903
1693/41903
1694/41903
1695/41903
1696/41903
1697/41903
1698/41903
1699/41903
1700/41903
1701/41903
1702/41903
1703/41903
1704/41903
1705/41903
1706/41903
1707/41903
1708/41903
1709/41903
1710/41903
1711/41903
1712/41903
1713/41903
1714/41903
1715/41903
1716/41903
1717/41903
1718/41903
1719/41903
1720/41903
1721/41903
1722/41903
1723/41903
1724/41903
1725/41903
1726/41903
1727/41903
1728/41903
1729/41903
1730/41903
1731/41903
1732/41903
1733/41903
1734/41903
1735/41903
1736/41903
1737/41903
1738/41903
1739/41903
1740/41903
1741/41903
1742/41903
1743/41903
1744/41903
1745/41903
1746/41903
1747/41903
1748/41903
1749/41903
1750/41903
1751/41903
1752/41903
1753/41903
1754/41903
1755/41903
1756/41903
1757/41903
1758/41903
1759/41903
1760/41903
1761/41903
1762/41903
1763/41903
1764/41903
1765/41903
1766/41903
1767/41903
1768/41903
1769/41903
1770/41903
1771/41903
1772/41903
1773/41903
1774/41903
1775/41903
1776/41903
1777/41903
1778/41903
1779/41903
1780/41903
1781/41903
1782/41903
1783/41903
1784/41903
1785/41903
1786/41903
1787/41903
1788/41903
1789/41903
1790/41903
1791/41903
1792/41903
1793/41903
1794/41903
1795/41903
1796/41903
1797/41903
1798/41903
1799/41903
1800/41903
1801/41903
1802/41903
1803/41903
1804/41903
1805/41903
1806/41903
1807/41903
1808/41903
1809/41903
1810/41903
1811/41903
1812/41903
1813/41903
1814/41903
1815/41903
1816/41903
1817/41903
1818/41903
1819/41903
1820/41903
1821/41903
1822/41903
1823/41903
1824/41903
1825/41903
1826/41903
1827/41903
1828/41903
1829/41903
1830/41903
1831/41903
1832/41903
1833/41903
1834/41903
1835/41903
1836/41903
1837/41903
1838/41903
1839/41903
1840/41903
1841/41903
1842/41903
1843/41903
1844/41903
1845/41903
1846/41903
1847/41903
1848/41903
1849/41903
1850/41903
1851/41903
1852/41903
1853/41903
1854/41903
1855/41903
1856/41903
1857/41903
1858/41903
1859/41903
1860/41903
1861/41903
1862/41903
1863/41903
1864/41903
1865/41903
1866/41903
1867/41903
1868/41903
1869/41903
1870/41903
1871/41903
1872/41903
1873/41903
1874/41903
1875/41903
1876/41903
1877/41903
1878/41903
1879/41903
1880/41903
1881/41903
1882/41903
1883/41903
1884/41903
1885/41903
1886/41903
1887/41903
1888/41903
1889/41903
1890/41903
1891/41903
1892/41903
1893/41903
1894/41903
1895/41903
1896/41903
1897/41903
1898/41903
1899/41903
1900/41903
1901/41903
1902/41903
1903/41903
1904/41903
1905/41903
1906/41903
1907/41903
1908/41903
1909/41903
1910/41903
1911/41903
1912/41903
1913/41903
1914/41903
1915/41903
1916/41903
1917/41903
1918/41903

In [26]:
map_k(recommended_list, watched_list, 10, len(df_iters_test['user_id'].unique()))

np.float64(0.11005305762855985)